-- Stored Procedures 02


ALTER PROCEDURE BuscarEnderecoPorEntidade @ENTIDADE AS VARCHAR(30)
AS
BEGIN
	IF @ENTIDADE = 'CLIENTE'
		SELECT Logradouro,Cidade, CEP, Pais FROM TB_ENDERECO WHERE ClienteId IS NOT NULL
	ELSE IF @ENTIDADE = 'FUNCIONARIO'
		SELECT Logradouro,Cidade, CEP, Pais FROM TB_ENDERECO WHERE FuncionarioId IS NOT NULL
	ELSE IF @ENTIDADE = 'FORNCEDORE'
		SELECT Logradouro,Cidade, CEP, Pais FROM TB_ENDERECO WHERE FuncionarioId IS NOT NULL
	ELSE
		SELECT 'OPÇÃO INVÁLIDA SELECIONE ALGUMA DESSA OPÇÕES, FUNCIONARIO OU FORNECEDOR'
END

EXEC BuscarEnderecoPorEntidade @ENTIDADE = 'FUNCIONARIO'


CREATE PROCEDURE CalcularIdade @IDADE AS INT OUTPUT, @DATA_NASCIMENTO AS DATETIME2
AS
BEGIN	
	SET @IDADE = DATEDIFF(YEAR,@DATA_NASCIMENTO, GETDATE())
END

DECLARE @IDADE_OUT AS INT = 0;

PRINT 'IDADE ANTES: ' + CAST(@IDADE_OUT AS VARCHAR(2))

EXEC CalcularIdade @IDADE_OUT OUTPUT, @DATA_NASCIMENTO = '1988-06-06'

PRINT 'IDADE DEPOIS: ' + CAST(@IDADE_OUT AS VARCHAR(2))