-- WITH ENCRYPTION
CREATE VIEW VIE_PEDI  WITH ENCRYPTION
AS
	SELECT P.NumeroPedido, P.DataPedido, F.NomeCompleto
		FROM TB_PEDIDO P
	JOIN TB_FUNCIONARIO F
			ON P.FuncionarioId = F.FuncionarioId

-- WITH SCHEMABINDING
ALTER TABLE TB_FUNCIONARIO
ADD TESTE VARCHAR(50) NULL

CREATE VIEW VIE_PED2
WITH ENCRYPTION, SCHEMABINDING
AS 
SELECT 
	F.NomeCompleto,  
	P.DataPedido, 
	F.TESTE
FROM TB_FUNCIONARIO F JOIN TB_PEDIDO P
ON F.FuncionarioId = p.FuncionarioId